import { bundle } from "@remotion/bundler";
import { getCompositions, renderMedia } from "@remotion/renderer";
import path from "path";
import fs from "fs-extra";

const runDualRender = async () => {
  const outDir = path.resolve("out");
  fs.ensureDirSync(outDir);

  const cacheDir = path.resolve(process.cwd(), "node_modules/.cache");
  if (fs.existsSync(cacheDir)) fs.removeSync(cacheDir);

  // Read the 2D and 3D scene data generated by Step 1
  const json2DPath = path.resolve("data/sceneData2D.json");
  const json3DPath = path.resolve("data/sceneData3D.json");

  const data2D = fs.existsSync(json2DPath)
    ? fs.readJsonSync(json2DPath)
    : {
        engine: "2D",
        title: "NEO CYBER GRAPHICS",
        theme: "cyberpunk",
        durationInFrames: 450,
        fps: 30,
        layout: { bgColor: "#09090f", textColor: "#ffffff", accentColor: "#ff0055" },
        shapes: { type: "circles", count: 12 },
        seoTags: ["2d", "motion", "cyber"]
      };

  const data3D = fs.existsSync(json3DPath)
    ? fs.readJsonSync(json3DPath)
    : {
        engine: "3D",
        title: "QUANTUM SINGULARITY",
        theme: "quantum_core",
        durationInFrames: 450,
        fps: 30,
        environment: { primaryColor: "#00ffcc", secondaryColor: "#ff0055" },
        mainGeometry: { shape: "quantum_rings", wireframe: true, rotationSpeed: 0.02 },
        vfx: { particleCount: 5000 },
        seoTags: ["3d", "webgl", "procedural"]
      };

  console.log("📦 Bundling Remotion project for Dual-Engine Rendering...");
  const bundleLocation = await bundle({
    entryPoint: path.resolve("./src/index.ts"),
    webpackOverride: (config) => config,
  });

  const chromiumOptions = {
    gl: "swangle" as const,
  };

  // -------------------------------------------------------------
  // RENDER 1: 2D MOTION GRAPHICS VIDEO (SVG/HTML)
  // -------------------------------------------------------------
  console.log("🎬 [1/2] RENDERING 2D MOTION GRAPHICS VIDEO...");
  const comps2D = await getCompositions(bundleLocation, {
    inputProps: { sceneData: data2D, data: data2D },
    chromiumOptions,
  });

  const comp2D = comps2D.find((c) => c.id === "SceneRouter" || c.id === "MasterScene2D" || c.id === "MasterScene") || comps2D[0];
  const output2D = path.join(outDir, "final_video_2D.mp4");

  await renderMedia({
    composition: comp2D,
    serveUrl: bundleLocation,
    codec: "h264",
    outputLocation: output2D,
    inputProps: { sceneData: data2D, data: data2D },
    crf: 16,
    chromiumOptions,
  });
  console.log(`✅ [1/2] 2D Video Rendered: ${output2D}`);

  // -------------------------------------------------------------
  // RENDER 2: 3D PROCEDURAL WEBGL VIDEO (Pure VFX, No Text)
  // -------------------------------------------------------------
  console.log("🎬 [2/2] RENDERING 3D PROCEDURAL WEBGL VIDEO...");
  const comps3D = await getCompositions(bundleLocation, {
    inputProps: { sceneData: data3D, data: data3D },
    chromiumOptions,
  });

  const comp3D = comps3D.find((c) => c.id === "SceneRouter" || c.id === "MasterScene3D" || c.id === "MasterScene") || comps3D[0];
  const output3D = path.join(outDir, "final_video_3D.mp4");

  await renderMedia({
    composition: comp3D,
    serveUrl: bundleLocation,
    codec: "h264",
    outputLocation: output3D,
    inputProps: { sceneData: data3D, data: data3D },
    crf: 16,
    chromiumOptions,
  });
  console.log(`✅ [2/2] 3D Video Rendered: ${output3D}`);

  console.log("🎉 ALL DUAL-ENGINE RENDERS COMPLETED SUCCESSFULLY!");
};

runDualRender().catch((err) => {
  console.error("❌ Dual Render Error:", err);
  process.exit(1);
});
