import { bundle } from "@remotion/bundler";
import { getCompositions, renderMedia } from "@remotion/renderer";
import path from "path";
import fs from "fs-extra";

const run = async () => {
  const outDir = path.resolve("out");
  fs.emptyDirSync(outDir);

  const jsonPath = path.resolve("src/data/videoConfig.json");
  if (!fs.existsSync(jsonPath)) throw new Error("videoConfig.json missing! Run generator first.");
  const jsonData = fs.readJsonSync(jsonPath);

  console.log(`🧨 BYPASSING TEMPLATES. COMPILING AI-GENERATED BAWAL CODE...`);

  // Inject the raw, complex THREE.js code generated by the AI
  const componentCode = `
import React, { useEffect, useRef } from 'react';
import { useCurrentFrame, useVideoConfig } from 'remotion';
import * as THREE from 'three';

// --- AI GENERATED MARKET-DRIVEN VISUAL ---
${jsonData.reactCode}
  `;
  fs.writeFileSync(path.resolve("src/BawalAsset.tsx"), componentCode);
  
  // Dynamic entry point for Remotion
  const dynamicEntryCode = `
import { registerRoot, Composition } from 'remotion';
import { BawalAsset } from './BawalAsset';

const RemotionRoot = () => (
  <Composition id="MarketDomination" component={BawalAsset} durationInFrames={300} fps={30} width={3840} height={2160} />
);
registerRoot(RemotionRoot);
  `;
  fs.writeFileSync(path.resolve("src/dynamic_entry.tsx"), dynamicEntryCode);

  console.log("📦 Bundling Commercial-Grade WebGL Asset...");
  const bundled = await bundle({ entryPoint: path.resolve("./src/dynamic_entry.tsx"), webpackOverride: (config) => config });

  // Bulletproof Headless Flags for Heavy 3D Math
  const chromiumOptions = {
    gl: "angle",
    args: [
      "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu", 
      "--use-gl=angle", "--use-angle=swiftshader", "--disable-features=Vulkan", 
      "--disable-web-security", "--force-color-profile=srgb", "--enable-webgl"
    ]
  };

  const comps = await getCompositions(bundled, { chromiumOptions });

  console.log(`🎯 RENDERING 4K MASTERPIECE FOR ADOBE STOCK...`);
  await renderMedia({
    composition: comps[0], 
    serveUrl: bundled, 
    codec: "h264", 
    bitrate: "100M", // Boosted for ultimate 4K quality
    concurrency: 1,
    outputLocation: path.join(outDir, "final_commercial_master.mp4"), 
    chromiumOptions
  });

  const metadata = `TITLE:\n${jsonData.title}\n\nSTRATEGY:\n${jsonData.demandAnalysis}\n\nTAGS:\n${(jsonData.seoTags || []).join(", ")}\n`;
  fs.writeFileSync(path.join(outDir, "metadata.txt"), metadata);
  console.log("✅ Video rendered successfully. Ready to mint money on Adobe Stock!");
};

run().catch((err) => {
  console.error("❌ Render Error:", err);
  process.exit(1);
});
