import { bundle } from "@remotion/bundler";
import { getCompositions, renderMedia } from "@remotion/renderer";
import path from "path";
import fs from "fs-extra";
import crypto from "crypto";

const runRender = async () => {
  const outDir = path.resolve("out");
  fs.ensureDirSync(outDir);

  const cacheDir = path.resolve(process.cwd(), "node_modules/.cache");
  if (fs.existsSync(cacheDir)) fs.removeSync(cacheDir);

  // Read sceneData generated by 1_generateJson.ts if present
  const sceneDataPath = path.resolve("data/sceneData.json");
  let parsedJson: any = null;
  if (fs.existsSync(sceneDataPath)) {
    try {
      parsedJson = fs.readJsonSync(sceneDataPath);
    } catch {
      parsedJson = null;
    }
  }

  // Generate a totally unique ID for EVERY single render run
  const uniqueSeed = crypto.randomUUID();
  const timestamp = Date.now();

  console.log(`🎯 RENDERING UNIQUE VIDEO WITH SEED: ${uniqueSeed}`);

  console.log("📦 Bundling Remotion project for 4K dynamic render...");
  const bundled = await bundle({
    entryPoint: path.resolve("./src/index.ts"),
    webpackOverride: (config) => config,
  });

  const inputProps = {
    sceneData: parsedJson,
    data: parsedJson,
    seed: uniqueSeed,
    themeColor: parsedJson?.lighting?.colorTheme || (Math.random() > 0.5 ? "hotpink" : "cyan"),
  };

  const comps = await getCompositions(bundled, {
    inputProps,
    chromiumOptions: {
      gl: "swangle",
    },
  });

  const videoComp = comps.find((c) => c.id === "MasterScene") || comps[0];

  if (!videoComp) {
    throw new Error("No composition found to render!");
  }

  const outputLocation = path.join(outDir, `video_${timestamp}.mp4`);

  await renderMedia({
    composition: videoComp,
    serveUrl: bundled,
    codec: "h264",
    outputLocation,
    inputProps,
    crf: 16,
    chromiumOptions: {
      gl: "swangle",
    },
  });

  console.log(`✅ 4K UNIQUE CLOUD RENDER DONE: ${outputLocation}`);
};

runRender().catch((err) => {
  console.error("❌ Render Error:", err);
  process.exit(1);
});
